### ISSUE TITLE
SERVER SIDE ERROR: Unknown column in field list

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#13]
Once I changed the columns of the object to display the data I got an error without the possibility to find the source of it. 
Quitting the server and the client before relaunching them solves this error. 
![Capture d’écran 2021-09-17 à 11 25 57](https://user-images.githubusercontent.com/50170060/134005667-60bb65a1-d05b-488c-8ac7-d45f28e535da.png)

**Comment by brunobuddy** [comment]
Same as https://github.com/case-app/nest-library/issues/1
