### ISSUE TITLE
Schematics>Error in Terminal 

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#163]
This error occurs often in the terminal, it's appear and disappear without letting know why and how. We can still work properly even if the error occurs. May be we can check in schematics if we can avoid it.

<img width="1023" alt="Capture d’écran 2022-07-11 à 09 27 59" src="https://user-images.githubusercontent.com/50170060/178211307-d7f1815e-85b3-4cf3-b76c-5db9917abf23.png">

**Comment by brunobuddy** [comment]
Duplicate with #67
