### ISSUE TITLE
files of ressource in camelCase are wrongly imported

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#175]
When resource is in 2 words, the resource.definition file is in kebab-case but this same file is imported in resource.create-edit, yields, controller and list in camelCase

The resource.definition Slug shouldn't be in kebab case but in camelCase

**Comment by brunobuddy** [comment]
@ismaelguerrib I do not understand the problem. Can you be more precise about the problem you want to solve ?

Regarding your last sentence, the resource definition slug is used to generate endpoints url. Example: for "Use cases" it will make requests like GET /use-cases/:id, that why we use kebbab case rather that camel case
