### ISSUE TITLE
Resource.service : show function is using either createQueryBuilder or findOneOrFail

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#177]

**Comment by brunobuddy** [comment]
@ismaelguerrib I do not understand this issue. What is the problem you want to solve ?

**Comment by brunobuddy** [comment]
@SebConejo

**Comment by SebConejo** [comment]
@brunobuddy why am I tagged ? @ismaelguerrib you wrote yourself this issue.
![Capture d’écran 2022-09-13 à 12 19 29](https://user-images.githubusercontent.com/11723962/189876970-e92afef5-80d2-4957-b4b4-228287d5fe81.png)

**Comment by brunobuddy** [comment]
It was a test, you were there too 😁😁
