### ISSUE TITLE
Filter > params orderBy and orderByAsc or orderByDesc don't filter the selectOptions

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#178]
I would like to display the options of the Multiselect or the Select or the MultiSearch by alphabetical order, so I add the properties like follow but it's not working : 

 ```
{
      label: `filter label name`,
      property: 'filterLabelIds',
      inputType: InputType.MultiSelect,
      className: 'is-3',
      selectOptions: () =>
        this.componentResourceService.listSelectOptions('users', {
          roleNames: [
            appConstants.ROLES.ADMIN_ROLE_NAME,
            appConstants.ROLES.BUSINESS_ENGINEER_ROLE_NAME
          ],
          includeNotActive: 'true',
          orderBy: 'isActive',
          orderByDesc: 'true'
        })
    }

```
The params are well send to API but the response don't take them in count. 

![Capture d’écran 2022-08-22 à 15 55 14](https://user-images.githubusercontent.com/50170060/185950427-1e2edb47-edbf-472e-ac68-7893c7010267.png)

**Comment by brunobuddy** [comment]
@ismaelguerrib it is not supposed to work out of the box.

If you want to add sorting to the listSelectOptions, you should update the listSelectOptions() function in the `myResource.controller.ts` to allow the new query param and then add the logic to it.

Do you think that orderBy should be a default function on listSelectOptions ? If yes we can planify this feature. If you think rather that the feature is not well enough documented, you can propose to [improve the documentation](https://docs.case.app/#/resources/relations?id=filter-by-relation)

**Comment by brunobuddy** [comment]
After verification the listSelectOptions() function already allows orderBy et orderByDesc query params.
