### ISSUE TITLE
datepicker from to : Impossible to open the 2nd date picker. 

### ISSUE THREAD

**Issue by SebConejo** [case-app/case#2]
when you click on the right datepicker (TO), the left one (FROM) opens.
![Capture d’écran 2021-08-17 à 15 52 51](https://user-images.githubusercontent.com/11723962/129738269-e850e996-3b18-46d1-813b-950267faa8fe.png)

**Comment by brunobuddy** [comment]
@SebConejo components are in Angular Library, please open this issue in the https://github.com/case-app/angular-library repo and close this one.
