### ISSUE TITLE
The flash message appears on top of the list pagination

### ISSUE THREAD

**Issue by brunobuddy** [case-app/case#23]
It should appear somewhere else as it is confusing

![Screenshot from 2021-10-28 17-40-24](https://user-images.githubusercontent.com/6626184/139289691-d4c94cfa-3f20-4e1a-8f8b-91e8b122acff.png)

**Comment by SebConejo** [comment]
@brunobuddy I don't know if it's a bug or not. I thought about 2 solutions: 
 - 1 - Put the notification to the right or left side with a smaller width 
 - 2 - Add a close button to the notification. In this case you have to work on it...
 
 Here is a screenshot with the notiification at the bottom right / left of the page.
 
![Capture d’écran 2022-01-12 à 18 36 42](https://user-images.githubusercontent.com/11723962/149192904-0a1f4476-71d4-4d49-a668-16c74726c3e9.png)
![Capture d’écran 2022-01-12 à 18 36 40](https://user-images.githubusercontent.com/11723962/149192914-30a62a2a-74ce-47fc-9524-67ea8e3e2b38.png)

**Comment by SebConejo** [comment]
J'ai calé la noti
