### ISSUE TITLE
List: Action menu goes behind card on lasts items (z-index)

### ISSUE THREAD

**Issue by brunobuddy** [case-app/case#46]

**Comment by SebConejo** [comment]
It's an issue I wrote for you on october 21 :->  https://github.com/case-app/angular-library/issues/6. We talked about it several times.

I can't solve it using CSS. We have to create a dropdown not nested with a dynamic position.

**Comment by brunobuddy** [comment]
@SebConejo doing a JS-based dropdown menu seams a lot of work for that issue. I added a class to each <tr> to be able to select the last(s) dropdown(s) and to display them a bit higher.

Classes are set in this way:
- "pos-$number": item position in list, starting by 0
- "rev-pos-$number": item reverse position in list, ending by 0

![image](https://user-images.githubusercontent.com/6626184/150113771-df4cbfb3-7bc4-4a28-a373-a2b997150954.png)
