### ISSUE TITLE
Breadcrumbs : last part not showing on create/edit resource

### ISSUE THREAD

**Issue by brunobuddy** [case-app/case#49]

**Comment by brunobuddy** [comment]
@SebConejo I did my part, we just need to style the <span> elements (when there is no link on breadcrumb element)

![image](https://user-images.githubusercontent.com/6626184/149981611-13c8ced4-9778-4739-8cfa-a015b81660c6.png)

**Comment by SebConejo** [comment]
@brunobuddy Que se passe-t-il avec les breadcrumbs ? Ca fait 3 fois que je les répare sur case. Si vous touchez aux breadcrumbs pour une raisons ou une autre, il faut absolument respecter la sémantique HTML de bulma et tout devrait fonctionner. --> [https://bulma.io/documentation/components/breadcrumb/](https://bulma.io/documentation/components/breadcrumb/)

**Comment by SebConejo** [comment]
Je n'arrive pas à voir ce qui a été retiré. Je ne comprends pas le pb

**Comment by brunobuddy** [comment]
@SebConejo the current problem concerns style, we need more whitespace https://github.com/case-app/case/issues/49#issuecomment-1015610294
