### ISSUE TITLE
Créer un nouveau Input "Google Place"

### ISSUE THREAD

**Issue by SebConejo** [case-app/case#51]

**Comment by brunobuddy** [comment]
Limit to France

**Comment by brunobuddy** [comment]
@SebConejo the input has been created, we need to add basic style and "show errors" version (red borders).

**Comment by SebConejo** [comment]
Il me faut une explication de ce composant. Je ne le trouve pas et je ne peux pas deviner comment il fonctionne, comment je peux le styliser.

**Comment by SebConejo** [comment]
- [ ] Comment changer l'icone ? Celle par défaut est trop dégueulasse
- [ ] La recherche ne fonctionne pas bien. Je ne trouve pas d'adresse. Les résultats sont bizarres.
- [ ] La div qui doit recevoir des classes est celle de l'input (pas un parent). Donc toutes les classes dynamiques doivent modifier ce tag la. Les classes qu'on utilise actuellement dans le framework sont des classes de couleurs (is-danger) et des classes de taille (is-small)
- [ ]

**Comment by brunobuddy** [comment]
@SebConejo maybe @XaviLami's solution with Geoapify does not meet the requirements. We should talk about this and leave it for later. 

I am removing this issue from the v0.2 milestone.
