### ISSUE TITLE
"Google Place": The firm icone should be replaced a mapker icon. How would we implement it ?

### ISSUE THREAD

**Issue by SebConejo** [case-app/case#77]
The svg map pin icon :

` <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-map-pin"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>`

Angular component doc : https://apidocs.geoapify.com/samples/autocomplete/autocomplete-tutorial/#step-1

**Comment by brunobuddy** [comment]
Related to #51
