### ISSUE TITLE
Improve webpack config 

### ISSUE THREAD

**Issue by SebConejo** [case-app/case#8]
It takes too much time to work on the project with the actual configuration
- [ ] Working on the css is taking too long. For each modification, you have to build the library and restart the case project

**Comment by brunobuddy** [comment]
@SebConejo it is not webpack related but more about the "npm link" command.

2 steps are required when working on Angular Library SCSS files :
- Compile Angular Library styles
- Once done, reload the case-app/case "ng serve"

Indeed it takes too long, maybe we can find some infos on the web

**Comment by brunobuddy** [comment]
This issue is related to https://github.com/case-app/angular-library repository. Closing
