### ISSUE TITLE
Yields > Image : We can't display the image and it's label side to side

### ISSUE THREAD

**Issue by ismaelguerrib** [case-app/case#81]
I want to display an image and it label side to side such as it's show in the [doc ](https://case-app.github.io/docs/#/list/yields?id=image)

I have the image and its label because the tooltip is displaying the name corresponding to the business engineer avatar. 
But I don't know how to display it aside.

I followed the instructions and here is my code : 

![Capture d’écran 2022-02-01 à 11 27 01](https://user-images.githubusercontent.com/50170060/151953478-91220253-c232-452f-9cda-1a72ce0b9341.png)
![Capture d’écran 2022-02-01 à 11 28 25](https://user-images.githubusercontent.com/50170060/151953480-e6a0381f-5bf8-4170-9bb4-2e90e36082cc.png)
![Capture d’écran 2022-02-01 à 11 27 29](https://user-images.githubusercontent.com/50170060/151953481-1300d5cd-5889-405d-9a06-670276ce439c.png)

**Comment by brunobuddy** [comment]
@ismaelguerrib check the user list, it seems that it implements this layout

**Comment by ismaelguerrib** [comment]
[Here 's](https://docs.google.com/document/d/1hFJHCbKyRO4S8E0Tm6UgNwjLAFJE1DW5t3XFaihzMvo/edit?usp=sharing) a refactoring proposition

**Comment by SebConejo** [comment]
@ismaelguerrib En voyant l'issue 33 ca semble toujours ne pas fonctionner. Je bascule la task dans Todo du coup.

**Comment by SebConejo** [comment]
@brunobuddy we don't know if this task is done because the feature doesn't work in our current project using CASE. Can you make sure it works and if it is, update the documentation ?

**Comment by brunobuddy** [comment]
Closing this issue as it became too hard to understand what is requested and what's done. Please re-open an issue with expectations and the current behavior
